substitutions:
  device_type: "device"
  device_type_nice: "Device"
  device_name: ${sys_name}_${device_type}
  friendly_name: "${nice_name} ${device_type_nice}"

logger:

text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version
    id: ${device_name}_esphome_version
    icon: mdi:home

button:
  - platform: restart
    id: ${device_name}_restart_button
    icon: mdi:restart
    name: "${friendly_name} Restart"

packages:
  names: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/names.yaml
    refresh: 1s
  time: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/time.yaml
    refresh: 1s
  network: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/network.yaml
    refresh: 1d