#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
#provided as is, but feel free to learn, copy, and use, but at own risk.
#this file has stuff used in pretty much every ESP8266 yaml file I have.
esphome:
  name: ${name}
  comment: ${friendly_name}
  platform: ESP8266
  board: esp01_1m


i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ntc
    sensor: ${device_name}_temp_resistance_reading
    name: "${nice_name} ESP Temperature"
    id: ${device_name}_esp_temp
    unit_of_measurement: "°c"
    accuracy_decimals: 1
    device_class: temperature
    icon: "mdi:thermometer"
    calibration:
  - platform: resistance
    id: ${device_name}_temp_resistance_reading
    sensor: ${device_name}_temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: ${device_name}_temp_analog_reading
    pin: A0

packages:
  base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/base.yaml
    refresh: 0s