#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
#provided as is, but feel free to learn, copy, and use, but at own risk.
#this file has stuff used in pretty much every ESP8266 yaml file I have.
substitutions:
  esp_board: "esp01_1m"
  esp8266_disable_ssl_support: "true"
  http_request_timeout: "2s"

esphome:
  name: ${name}
  comment: ${friendly_name}

esp8266:
  board: ${esp_board}
  restore_from_flash: true
  framework:
    version: recommended


packages:
  base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/base.yaml
    refresh: 1s

http_request:
  id: http_request_data
  useragent: esphome/device
  timeout: ${http_request_timeout}
  esp8266_disable_ssl_support: ${esp8266_disable_ssl_support}

sensor:
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

