#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
#provided as is, but feel free to learn, copy, and use, but at own risk.
#this file has stuff used in pretty much every ESP8266 yaml file I have.
substitutions:
  nice_name: "ESPHome"
  sys_name: "esphome"
  device_type: "device"
  device_type_nice: "Device"
  name: ${sys_name}-${device_type}
  friendly_name: "${nice_name} ${device_type_nice}"

esphome:
  name: ${name}
  comment: ${friendly_name}
  platform: ESP8266
  board: esp01_1m

packages:
  base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/base.yaml
    refresh: 0s
  time: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/time.yaml
    refresh: 0s
  network: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/network.yaml
    refresh: 0s