substitutions:
  nice_name: "ESPHome"
  sys_name: "esphome"
  device_type: "device"
  device_type_nice: "Device"
  device_name: ${sys_name}_${device_type}
  id: ${device_name}
  name: ${sys_name}-${device_type}
  friendly_name: "${nice_name} ${device_type_nice}"
  friendly_relay_name_1: "${friendly_name}"
  device_relay_name_1: "${device_name}"
  friendly_relay_name_2: "${friendly_name}"
  device_relay_name_2: "${device_name}"
