substitutions:
  web_server_port: "80"
  ssid: "IP freely"
  password: "ewwwwwwwww"
  domain: ".local"
  power_save_mode: "high"
  ota_password: "wouldn't you like to know?"

ota:
  password:  ${ota_password}
  id: ota_id
  platform: esphome

captive_portal:
  id: capitive_portal_id


sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    id: ${sys_name}_${device_type}_wifi_signal
    icon: mdi:wifi
    update_interval: 60s

text_sensor:
  - platform: template
    name: "${friendly_name} Hostname"
    id: ${device_name}_hostname
    icon: mdi:ip-network
    lambda: return {"${name}${domain}"};
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      id: ${device_name}_ip_address
      icon: mdi:wifi
    ssid:
      name: ${friendly_name} AP
      id: ${device_name}_ssid
      icon: mdi:wifi
    bssid:
      name: ${friendly_name} AP MAC
      id: ${device_name}_bssid
      icon: mdi:wifi
    mac_address:
      name: ${friendly_name} MAC Address
      id: ${device_name}_mac
      icon: mdi:ip-network
    scan_results:
      name: ${friendly_name} APs Available
      id: ${device_name}_scan
      icon: mdi:wifi
