substitutions:
  nice_name: "ESPHome"
  sys_name: "esphome"
  device_type: "device"
  device_type_nice: "Device"
  device_name: ${sys_name}_${device_type}
  name: ${sys_name}-${device_type}
  friendly_name: "${nice_name} ${device_type_nice}"
  web_server_port: "80"
  ssid: "IP freely"
  password: "ewwwwwwwww"
  domain: ".local"
  power_save_mode: "high"
  esp8266_disable_ssl_support: "true"
  http_request_timeout: "2s"
  ota_password: "wouldn't you like to know?"

api:
  password:  ${ota_password}

ota:
  password:  ${ota_password}

captive_portal:

wifi:
  ssid: ${ssid}
  password: ${password}
  domain: ${domain}
  ap:
    ssid: "${friendly_name} Fallback"
    password: ${password}
  power_save_mode: ${power_save_mode}

web_server:
  port: ${web_server_port}

http_request:
  id: http_request_data
  useragent: esphome/device
  timeout: ${http_request_timeout}
  esp8266_disable_ssl_support: ${esp8266_disable_ssl_support}

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    id: ${sys_name}_${device_type}_wifi_signal
    icon: mdi:wifi
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      id: ${device_name}_ip_address
      icon: mdi:ip-network
    ssid:
      name: ${friendly_name} SSID
      id: ${device_name_ssid
      icon: mdi:ip-network
    bssid:
      name: ${friendly_name} BSSID
      id: ${device_name_bssid
      icon: mdi:ip-network
    mac_address:
      name: ESP Mac Wifi Address
      name: ${friendly_name} MAC Address
      id: ${device_name_mac
      icon: mdi:ip-network
    scan_results:
      name: ${friendly_name} Wifi Scan Results
      id: ${device_name_scan
      icon: mdi:ip-network
  - platform: template
    name: "${friendly_name} Hostname"
    id: ${device_name}_hostname
    icon: mdi:ip-network
    lambda: return {"${name}${domain}"};