substitutions:
  web_server_port: "80"
  ssid: "IP freely"
  password: "ewwwwwwwww"
  domain: ".local"
  power_save_mode: "high"
<<<<<<< HEAD
=======
  http_request_timeout: "2s"
>>>>>>> e30ac66ac6bb0f667d5c86cb56d768e0ef1de227
  ota_password: "wouldn't you like to know?"

api:
  id: api_id

ota:
  password:  ${ota_password}
  id: ota_id

captive_portal:
  id: capitive_portal_id

wifi:
  id: wifi_id
  ssid: ${ssid}
  password: ${password}
  domain: ${domain}
  ap:
    ssid: "${friendly_name}"
    password: ${password}
  power_save_mode: ${power_save_mode}

web_server:
  port: ${web_server_port}

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    id: ${sys_name}_${device_type}_wifi_signal
    icon: mdi:wifi
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      id: ${device_name}_ip_address
      icon: mdi:wifi
    ssid:
      name: ${friendly_name} AP
      id: ${device_name}_ssid
      icon: mdi:wifi
    bssid:
      name: ${friendly_name} AP MAC
      id: ${device_name}_bssid
      icon: mdi:wifi
    mac_address:
      name: ${friendly_name} MAC Address
      id: ${device_name}_mac
      icon: mdi:ip-network
    scan_results:
      name: ${friendly_name} APs Available
      id: ${device_name}_scan
      icon: mdi:wifi
  - platform: template
    name: "${friendly_name} Hostname"
    id: ${device_name}_hostname
    icon: mdi:ip-network
    lambda: return {"${name}${domain}"};
