substitutions:
  home_assistant_host: "home.lan"
  ping_rate: 16sec

esphome:
  libraries:
    - ESP8266WiFi
    - https://github.com/akaJes/AsyncPing#95ac7e4

sensor:
  - platform: ping
    ip_address: ${home_assistant_host}
    num_attempts: 1
    timeout: 1sec
    loss:
      name: "${nice_name} Packet Loss"
      id: "${sys_name}_packet_loss"
      icon: mdi:lan-check
    latency:
      name: "${nice_name} Latency"
      id: "${sys_name}_latency"
      accuracy_decimals: 3
      icon: mdi:lan-check

    update_interval: ${ping_rate}

external_components:
  - source: github://trombik/esphome-component-ping
    components: [ ping ]