#source for orginal: https://www.esphome-devices.com/devices/Shelly-1PM
#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
substitutions:
  device_type: "switch"
  device_type_nice: "Switch"
  max_temp: "70.0"
  max_power_1: "1600.0"
  restore_mode_1: "ALWAYS_ON"
  relay_gpio_1: "GPIO15"

globals:
   - id: too_hot_boolean
     type: bool
     restore_value: true
     initial_value: 'false'


switch:
  - platform: gpio
    name: "${friendly_relay_name_1} Relay"
    pin: ${relay_gpio_1}
    id: ${device_relay_name_1}_shelly_relay
    icon: "mdi:electric-switch"
    restore_mode: ${restore_mode_1}

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${friendly_name} Shelly Temperature"
    unit_of_measurement: "°c"
    accuracy_decimals: 1
    device_class: temperature
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - globals.set:
              id: too_hot_boolean
              value: 'true'
          - switch.turn_off: ${device_relay_name_1}_shelly_relay
          - switch.turn_off: ${device_relay_name_2}_shelly_relay
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Switch turned off because temperature exceeded ${max_temp}°C
          - homeassistant.event:
              event: esphome.overheat
              data:
                title: "${friendly_name} has overheated."
      - below: ${max_temp}
        then:
          - globals.set:
              id: too_hot_boolean
              value: 'false'

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true


packages:
  base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/esp8266.yaml
    refresh: 1s
  light_settings: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/light_settings.yaml
    refresh: 1s