#source for orginal: https://www.esphome-devices.com/devices/Shelly-1PM
#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
substitutions:
  device_type: "switch"
  device_type_nice: "Switch"
  max_temp: "70.0"
  max_power_1: "1600.0"
  restore_mode_1: "ALWAYS_ON"
  light_automation_input_number_max_1: '2'
  scene_light_host_string_1: ""
  scene_master_host_1: ""
  light_settings_string_1: '{{"light.turn_off"},{"light.turn_on","kelvin","2700","brightness_pct","30"},{"light.turn_on","kelvin","4587","brightness_pct","100"}}'
  light_entities_count_1: "2"
  scene_icon_1: "mdi:ceiling-light-outline"
  external_switch_gpio_1: "GPIO4"
  relay_gpio_1: "GPIO15"
  light_name_1: "light.${sys_name}"

globals:
   - id: too_hot_boolean
     type: bool
     restore_value: true
     initial_value: 'false'
   - id: ${device_relay_name_1}_scene_light_host_string
     type: const std::vector<std::string>
     initial_value: ${scene_light_host_string_1}
   - id: ${device_relay_name_1}_light_settings_string
     type: const std::vector<std::vector<std::string>>
     initial_value: ${light_settings_string_1}
   - id: ${device_relay_name_1}_scene_master_host
     type: std::string
     initial_value: ${scene_master_host_1}
   - id: edge_switch_1
     type: bool
     restore_value: true
     initial_value: 'false'
   - id: old_x_1
     type: int
     restore_value: true
     initial_value: 'false'

esphome:
  on_boot:
    priority: 200
    then:
       - if:
            condition:
              - lambda: return (0.0 != id(${device_relay_name_1}_scene).state);
            then:
              - switch.turn_on: ${device_relay_name_1}_shelly_relay

switch:
  - platform: gpio
    pin: GPIO16
    name: "ade7953 IRQ pin"
    internal: true
  - platform: gpio
    name: "${friendly_relay_name_1} Relay"
    pin: ${relay_gpio_1}
    id: ${device_relay_name_1}_shelly_relay
    icon: "mdi:electric-switch"
    restore_mode: ${restore_mode_1}
  - platform: template
    name: "${friendly_relay_name_1} Switch Edge Mode"
    id: "${device_relay_name_1}_switch_edge_mode"
    optimistic: false
    restore_state: false
    turn_on_action:
      - globals.set:
          id: edge_switch_1
          value: 'true'
    turn_off_action:
      - globals.set:
          id: edge_switch_1
          value: 'false'
    lambda: |-
      return id(edge_switch_1);

number:
  - platform: template
    name: "${friendly_relay_name_1} Scene"
    id: "${device_relay_name_1}_scene"
    icon: "${scene_icon_1}"
    optimistic: true
    min_value: 0
    max_value: ${light_automation_input_number_max_1}
    restore_value: false
    initial_value: 1
    step: 1
    on_value:
      then:
          - lambda: |-
                        if(id(${device_relay_name_1}_scene).state == id(old_x_1)) {
                           return;
                        }

                        id(old_x_1) = x;
                        if(id(${device_name}_sun_enabled) && (id(sun_id).elevation() > ${day_elevation}) && (1 == x) && (id(${device_relay_name_1}_scene).traits.get_max_value() > 1)) {
                           id(${device_relay_name_1}_scene).make_call().number_increment(false).perform();
                           return;
                        }

                        bool relayNoFlip = false;
                        if((${light_entities_count_1} > 0) && id(api_id).is_connected()) {
                          id(${device_relay_name_1}_shelly_relay).turn_on();
                          const std::vector<std::string> attributes = id(${device_relay_name_1}_light_settings_string)[int(x)];
                          int index = 1;
                          HomeassistantServiceResponse resp;
                          resp.service = attributes[0];
                          HomeassistantServiceMap entity_key_value;
                          entity_key_value.key = "entity_id";
                          while(index <= ${light_entities_count_1}) {
                                entity_key_value.value += "${light_name_1}" + std::to_string(index);
                                if(index < ${light_entities_count_1})  {
                                  entity_key_value.value += ",";
                               }
                                index++;
                            }
                            resp.data.push_back(entity_key_value);
                            index = 1;
                            while(index < attributes.size()) {
                                HomeassistantServiceMap attribute_key_value;
                                attribute_key_value.key = attributes[index++];
                                attribute_key_value.value = attributes[index++]; 
                                resp.data.push_back(attribute_key_value);
                            }
                            id(api_id).send_homeassistant_service_call(resp);
                            relayNoFlip = true;
                         }

                         if (( id(${device_relay_name_1}_scene_light_host_string).size() > 0)  && id(wifi_id).is_connected()) {
                            esphome::http_request::HttpRequestComponent httpRequestComponent = esphome::http_request::HttpRequestComponent();
                            httpRequestComponent.set_method("POST");
                            for(std::string host_path : id(${device_relay_name_1}_scene_light_host_string)) {
                                httpRequestComponent.set_url("http://" +host_path + "/set?value=" + std::to_string(int(x)));
                                httpRequestComponent.send({});
                            }
                            httpRequestComponent.close();
                            relayNoFlip = true;
                        }

                        if((!relayNoFlip && (0 == x)) || id(edge_switch_1)) {
                            if(0 == x) {
                                    id(${device_relay_name_1}_shelly_relay).turn_off();
                            }else if(id(${device_relay_name_1}_scene).traits.get_max_value() == x) {
                                    id(${device_relay_name_1}_shelly_relay).turn_on();
                            } else {
                                    id(${device_relay_name_1}_scene).make_call().number_to_max().perform();
                            }
                        }

sun:
  on_sunrise:
    - elevation: ${day_elevation} 
      then: 
        - if:
             condition:
               - lambda: return  id(${device_name}_sunrise_enabled);
             then:
               - number.set:
                   id: "${device_relay_name_1}_scene"
                   value: !lambda return id(${device_name}_sunrise_scene).state;

  on_sunset:
    - elevation: ${day_elevation} 
      then: 
        - if:
             condition:
               - lambda: return  id(${device_name}_sunset_enabled);
             then:
               - number.set:
                   id: "${device_relay_name_1}_scene"
                   value: !lambda return id(${device_name}_sunset_scene).state;

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${friendly_name} Shelly Temperature"
    unit_of_measurement: "°c"
    accuracy_decimals: 1
    device_class: temperature
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - globals.set:
              id: too_hot_boolean
              value: 'true'
          - switch.turn_off: ${device_relay_name_1}_shelly_relay
          - switch.turn_off: ${device_relay_name_2}_shelly_relay
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Switch turned off because temperature exceeded ${max_temp}°C
          - homeassistant.event:
              event: esphome.overheat
              data:
                title: "${friendly_name} has overheated."
      - below: ${max_temp}
        then:
          - globals.set:
              id: too_hot_boolean
              value: 'false'

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: ${external_switch_gpio_1}
    filters:
      - delayed_on_off: 50ms # small delay to prevent debouncing
    name: "${friendly_relay_name_1} External Switch"
    internal: false
    id: "${device_relay_name_1}_actual_switch"
    on_state:
      then:
      - number.increment:
          id: "${device_relay_name_1}_scene"
          cycle: true


packages:
  base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/esp8266.yaml
    refresh: 1s
  sun: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/sun.yaml
    refresh: 1s