substitutions:
  sunrise_enabled: "true"
  sunset_enabled: "true"
  latitude: 48.8584°
  longitude: 2.2945°
  day_elevation: "-0.833"

globals:
   - id: ${device_relay_name_1}_sun_enabled
     type: bool
     restore_value: true
     initial_value: 'false'
   - id: ${device_relay_name_1}_sunrise_enabled
     type: bool
     restore_value: true
     initial_value: 'false'
   - id: ${device_relay_name_1}_sunset_enabled
     type: bool
     restore_value: true
     initial_value: 'false'

sensor:
  - platform: sun
    name: "${friendly_name} Sun Elevation"
    id: "${sys_name}_elevation"
    type: elevation
    icon: "mdi:sun-angle"
  - platform: sun
    name: "${friendly_name} Sun Azimuth"
    id: "${sys_name}_azimuth"
    type: azimuth
    icon: "mdi:sun-angle"

text_sensor:
  - platform: sun
    name: "${friendly_name} Sunrise"
    id: "${sys_name}_sunrise"
    icon: "mdi:weather-sunset-up"
    type: sunrise
    filters:
      - lambda: |-
           char hours[3] = "  ";
           hours[0] = x[0];
           hours[1] = x[1];
           int hours24 = atoi(hours);
           int hours12 = ((hours24 == 0) || (hours24 == 12))?12:(hours24 % 12);
           itoa(hours12,hours,10);
           if(hours12 < 10) {
              x[0] = ' ';
              x[1] = hours[0];
           } else {
              x[0] = hours[0];
              x[1] = hours[1];
           }
           return x + ((hours24 < 12)?" AM":" PM");
  - platform: sun
    name: "${friendly_name} Sunset"
    id: "${sys_name}_sunset"
    icon: "mdi:weather-sunset-down"
    type: sunset
    filters:
      - lambda: |-
           char hours[3] = "  ";
           hours[0] = x[0];
           hours[1] = x[1];
           int hours24 = atoi(hours);
           int hours12 = ((hours24 == 0) || (hours24 == 12))?12:(hours24 % 12);
           itoa(hours12,hours,10);
           if(hours12 < 10) {
              x[0] = ' ';
              x[1] = hours[0];
           } else {
              x[0] = hours[0];
              x[1] = hours[1];
           }
           return x + ((hours24 < 12)?" AM":" PM");

sun:
  id: sun_id
  latitude: ${latitude}
  longitude: ${longitude}


switch:
  - platform: template
    name: "${friendly_relay_name_1} Sun Enabled"
    id: "${device_relay_name_1}_sun_switch_toggle"
    icon: "mdi:weather-sunny"
    optimistic: false
    restore_state: true
    turn_on_action:
      - globals.set:
          id: ${device_relay_name_1}_sun_enabled
          value: 'true'
    turn_off_action:
      - globals.set:
          id: ${device_relay_name_1}_sun_enabled
          value: 'false'
    lambda: |-
      return id(${device_relay_name_1}_sun_enabled);
  - platform: template
    name: "${friendly_relay_name_1} Sunrise Enabled"
    id: "${device_relay_name_1}_sunrise_switch_toggle"
    icon: "mdi:weather-sunset-up"
    optimistic: false
    restore_state: true
    turn_on_action:
      - globals.set:
          id: ${device_relay_name_1}_sunrise_enabled
          value: 'true'
    turn_off_action:
      - globals.set:
          id: ${device_relay_name_1}_sunrise_enabled
          value: 'false'
    lambda: |-
      return id(${device_relay_name_1}_sunrise_enabled);
  - platform: template
    name: "${friendly_relay_name_1} Sunset Enabled"
    id: "${device_relay_name_1}_sunset_switch_toggle"
    icon: "mdi:weather-sunset-down"
    optimistic: false
    restore_state: true
    turn_on_action:
      - globals.set:
          id: ${device_relay_name_1}_sunset_enabled
          value: 'true'
    turn_off_action:
      - globals.set:
          id: ${device_relay_name_1}_sunset_enabled
          value: 'false'
    lambda: |-
      return id(${device_relay_name_1}_sunset_enabled);