#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
#provided as is, but feel free to learn, copy, and use, but at own risk.
#this file has stuff used in pretty much every ESP8266 yaml file I have.
substitutions:
  nice_name: "ESPHome"
  sys_name: "esphome"
  device_type: "device"
  device_type_nice: "Device"
  device_name: ${sys_name}_${device_type}
  friendly_name: "${nice_name} ${device_type_nice}"
  time_server1: "0.pool.ntp.org"
  time_server2: "1.pool.ntp.org"
  time_server3: "2.pool.ntp.org"

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - ${time_server1}
      - ${time_server2}
      - ${time_server3}

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor
    id: ${device_name}_uptime_sensor
    icon: mdi:clock-start
    update_interval: 60s


text_sensor:
  - platform: template
    name: "${friendly_name} Current time"
    id: ${device_name}_current_time
    lambda: |-
      char str[17];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M", localtime(&currTime));
      return  { str };
    icon: mdi:clock
    update_interval: 60s