substitutions:
  light_group: "light.any_lights"
  
packages:
  device-base: 
    url: https://github.com/snetsplit/shelly-esphome
    file: yaml/1PM-base-with-HA-ping-sensor.yaml
    refresh: 0s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms # small delay to prevent debouncing
    name: "${friendly_name} External Switch"
    on_state:
      then:
      - if:
          condition:
            and:
              - wifi.connected:
              - api.connected:
              - switch.is_on: shelly_relay
              - lambda: return id(packet_loss).state < 100;
          then:
            - homeassistant.service:
                service: light.toggle
                data:
                  entity_id: ${light_group}
          else:
            - switch.toggle: shelly_relay
    internal: false
    id: switchid
