substitutions:
  home-assistant-ip: "192.168.1.1"
  
packages:
  device-base: 
    url: https://github.com/snetsplit/shelly-esphome
    file: yaml/1PM-base.yaml
    refresh: 0s

# Basic Config
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  libraries:
    - ESP8266WiFi
    - https://github.com/akaJes/AsyncPing#95ac7e4
    
sensor:
  - platform: ping

    # IP address of Home Assistant
    ip_address: ${home-assistant-ip}

    # number of packets to send
    num_attempts: 5

    # the timeout. however, this is not what you usually expect from `ping`
    # implementation: the timeout is also the interval to send packets. if you
    # set this value to 10 sec, and the network is fine (no packet loss), then
    # the component sends a packet at 10 sec interval, and the total time to
    # finish would be 10 sec * num_attempts = 10 * 17 = 170 sec.
    timeout: 1sec

    loss:
      # the name to be shown.
      id: packet_loss
      name: Packet loss

    latency:
      # the name to be shown.
      id: latency
      name: Latency
      # this should be 3 as the value is float, unit is sec, and the raw
      # values are in ms.
      accuracy_decimals: 3

    # the interval for checking the sensors. defaults to 60s.
    update_interval: 10s
