substitutions:
  light_automation_input_number: "input_number.foo"
  
packages:
  device-base: 
    url: https://github.com/snetsplit/shelly-esphome
    file: yaml/1PM-base-with-HA-ping-sensor.yaml
    refresh: 0s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms # small delay to prevent debouncing
    name: "${friendly_name} External Switch"
    on_state:
      then:
      - if:
          condition:
            and:
              - wifi.connected:
              - api.connected:
              - switch.is_on: shelly_relay
              - lambda: return id(packet_loss).state < 100;
          then:
          - if:
              condition:
                lambda: return states(${light_automation_input_number}) >= state_attr('${light_automation_input_number}','max');
              then:
                - homeassistant.service:
                    service: input_number.set_value                    
                       data_template:
                         entity_id: ${light_automation_input_number}
                         value: "{{ state_attr('${light_automation_input_number}','min'); }}"
              else:
                - homeassistant.service:
                    service: input_number.increment
                      data:
                        step: 1
                      target:
                        entity_id: ${light_automation_input_number}
          else:
            - switch.toggle: shelly_relay
    internal: false
    id: switchid
