substitutions:
  home_assistant_IP: "192.168.1.1"
  light_group: "light.any_lights"
  
packages:
  device-base: 
    url: https://github.com/snetsplit/shelly-esphome
    file: yaml/1PM-base.yaml
    refresh: 0s

esphome:
  libraries:
    - ESP8266WiFi
    - https://github.com/akaJes/AsyncPing#95ac7e4

external_components:
  - source: github://trombik/esphome-component-ping
    components: [ ping ]
    
sensor:
  - platform: ping
    ip_address: ${home_assistant_IP}
    num_attempts: 5
    timeout: 1sec

    loss:
      id: packet_loss
      name: "Home Assistant Packet Loss"

    latency:
      id: latency
      name: "Home Assistant Latency"
      accuracy_decimals: 3

    update_interval: 10s


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms # small delay to prevent debouncing
    name: "${friendly_name} External Switch"
    on_state:
      then:
      - if:
          condition:
            and:
              - wifi.connected:
              - api.connected:
              - switch.is_on: shelly_relay
              - lambda: return id(packet_loss).state < 100;
          then:
            - homeassistant.service:
                service: light.toggle
                data:
                  entity_id: ${light_group}
          else:
            - switch.toggle: shelly_relay
    internal: false
    id: switchid
