globals:
   - id: input_number_min
     type: int
     restore_value: no
     initial_value: ${light_automation_input_number_min}
   - id: input_number_max
     type: int
     restore_value: no
     initial_value: ${light_automation_input_number_min}
   - id: input_number
     type: int
     restore_value: yes
     initial_value: ${light_automation_input_number_max}

substitutions:
  light_automation_input_number: "input_number.foo"
  light_automation_input_number_min: '1'
  light_automation_input_number_max: '4'
  home_assistant_IP: "192.168.1.1"
  ping_rate: 10sec
  
packages:
  device-base: 
    url: https://github.com/snetsplit/shelly-esphome
    file: yaml/1PM-base.yaml
    refresh: 0s

esphome:
  libraries:
    - ESP8266WiFi
    - https://github.com/akaJes/AsyncPing#95ac7e4

external_components:
  - source: github://trombik/esphome-component-ping
    components: [ ping ]
    
sensor:
  - platform: ping
    ip_address: ${home_assistant_IP}
    num_attempts: 1
    timeout: ${ping_rate}

    loss:
      id: packet_loss
      name: "Home Assistant Packet Loss"

    latency:
      id: latency
      name: "Home Assistant Latency"
      accuracy_decimals: 3

    update_interval: 10s

     
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms # small delay to prevent debouncing
    name: "${friendly_name} External Switch"
    on_state:
      then:
      - lambda: |-
          id(input_number) += 1;
          if (id(input_number) > id(input_number_max) ) {
             id(input_number) = id(input_number_min);
          }
      - if:
          condition:
            and:
              - wifi.connected:
              - api.connected:
              - lambda: return id(packet_loss).state < 100;
          then:
            - number.increment:
                id: "${device_name}_toggle"
                cycle: true
                
          else:
            - switch.toggle: shelly_relay
    internal: false
    id: switchid

number:
  - platform: template
    name: "${friendly_name} Toggle"
    id: "${device_name}_toggle"
    optimistic: true
    min_value: 1
    max_value: 3
    restore_value: true
    step: 1
    on_value:
      then:
        - homeassistant.service:
            service: scene.turn_on
            data_template: 
              entity_id: !lambda  |- 
                int sceneNameLength = 64;
                char sceneNameCharBuffer[sceneNameLength]; 
                std::snprintf(sceneNameCharBuffer, sceneNameLength, "scene.${device_name}%.0f", x); 
                std::string sceneName = sceneNameCharBuffer;
                ESP_LOGI("scene", "Setting scene: %s", sceneName.c_str()); 
                return sceneName.c_str();

switch:
  - platform: template
    name: "Act like a dumb switch"
    lambda: |-
      if (id(some_binary_sensor).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: switch2
    turn_off_action:
      - switch.turn_on: switch1
