#source for orginal: https://www.esphome-devices.com/devices/Shelly-1PM
substitutions:
  devicename: "shelly-1pm"
  max_temp: "70.0"
  friendly_name: Shelly 1PM
  
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  comment: ${friendly_name}
    
logger:

api:

ota:

wifi:
  ssid: "example"
  password: "examplepass"
  power_save_mode: HIGH # for ESP8266 LOW/HIGH are mixed up, esphome/issues/issues/1532
  ap:
    ssid: "${friendly_name} Fallback"
    password: "examplepass"

web_server:
  port: 80
