#source for orginal: https://www.esphome-devices.com/devices/Shelly-1PM
#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
globals:
   - id: basic_edge_switch_toggle_boolean
     type: bool
     restore_value: true
     initial_value: 'false'
   - id: too_hot_boolean
     type: bool
     restore_value: false
     initial_value: 'false'
   - id: scene_light_index_1
     type: unsigned int
     restore_value: no
     initial_value: '0'
   - id: last_value_1
     type: unsigned int
     restore_value: no
     initial_value: '0'
   - id: scene_light_host_string_1
     type: const std::vector<std::string>
     initial_value: ${scene_light_host_string_1}
   - id: edge_switch
     type: bool
     restore_value: false
     initial_value: 'false'
   - id: scene_switch
     type: bool
     restore_value: false
     initial_value: 'false'
   - id: sun_enabled
     type: bool
     restore_value: false
     initial_value: 'false'
     
substitutions:
  device_type: "switch"
  device_type_nice: "Switch"
  max_temp: "80.0"
  max_power: "1600.0"
  restore_mode: RESTORE_DEFAULT_ON
  light_automation_input_number_min: '0'
  light_automation_input_number_max: '2'
  
  auto_off_boolean_1: "false"
  off_scene_1: '0'
  on_scene_1: '1'
  delay_time_1: "1min"
  scene_light_host_string_1: ""

  sunrise_scene: "0"
  sunset_scene: "1"
  
esphome:
  on_boot:
    priority: 200
    then:
       - if:
            condition:
              - lambda: return (${off_scene_1}.0 == id(${device_name}_scene).state);
            then:
              - switch.turn_on: shelly_relay_1
            else:


switch:
  - platform: gpio
    name: "${nice_name} Switch Relay"
    pin: GPIO15
    id: shelly_relay_1
    icon: "mdi:electric-switch"
    restore_mode: ${restore_mode}
    on_turn_on:
      - if:
           condition:
             - lambda: return (${auto_off_boolean_1} && (${off_scene_1}.0 == id(${device_name}_scene).state));
           then:
             - number.set:
                 id: "${device_name}_scene"
                 value: ${on_scene_1}
  - platform: template
    name: "${nice_name} Switch Edge Mode"
    id: "basic_edge_switch_toggle_switch"
    optimistic: false
    restore_state: true
    turn_on_action:
      - globals.set:
          id: edge_switch
          value: 'true'
    turn_off_action:
      - globals.set:
          id: edge_switch
          value: 'false'
    lambda: |-
      return id(edge_switch);
  - platform: template
    name: "${nice_name} Scene"
    id: "scene_switch_toggle"
    optimistic: false
    restore_state: true
    turn_on_action:
      - globals.set:
          id: scene_switch
          value: 'true'
    turn_off_action:
      - globals.set:
          id: scene_switch
          value: 'false'
    lambda: |-
      return id(scene_switch);
  - platform: template
    name: "${nice_name} Sun Enabled"
    id: "sun_switch_toggle"
    optimistic: false
    restore_state: true
    turn_on_action:
      - globals.set:
          id: sun_enabled
          value: 'true'
    turn_off_action:
      - globals.set:
          id: sun_enabled
          value: 'false'
    lambda: |-
      return id(sun_enabled);
      return id(basic_edge_switch_toggle_boolean);
      
sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${nice_name} Temperature"
    unit_of_measurement: "°c"
    accuracy_decimals: 1
    device_class: temperature
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - globals.set:
              id: too_hot_boolean
              value: 'true'
          - switch.turn_off: shelly_relay_1
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Switch turned off because temperature exceeded ${max_temp}°C
          - homeassistant.event:
              event: esphome.overheat
              data:
                title: "${friendly_name} has overheated."
      - below: ${max_temp}
        then:
          - globals.set:
              id: too_hot_boolean
              value: 'false'




number:
  - platform: template
    icon: "mdi:bulb-group-outline"
    name: "${nice_name} Switch Scene"
    id: "${device_name}_scene"
    optimistic: true
    min_value: ${light_automation_input_number_min}
    max_value: ${light_automation_input_number_max}
    restore_value: true
    step: 1
    on_value:
      then:
          - lambda: |-
                        if(id(sun_enabled) && (id(sun_id).elevation() < 0) && (1 == x) && (${light_automation_input_number_max} > 1)) {
                           id(${device_name}_scene).state =2;
                           x = 2;
                        }
                        if(!id(edge_switch) && id(scene_switch) && id(api_id).is_connected()) {
                            HomeassistantServiceResponse resp;
                            resp.service = "scene.turn_on";
                            HomeassistantServiceMap entity_id_kv;
                            entity_id_kv.key = "entity_id";
                            entity_id_kv.value ="scene.${device_name}" + std::to_string(int(x));
                            resp.data.push_back(entity_id_kv);
                            id(api_id).send_homeassistant_service_call(resp);
                            return;
                         } else if (!id(edge_switch) && id(wifi_id).is_connected()) {
                            esphome::http_request::HttpRequestComponent httpRequestComponent = esphome::http_request::HttpRequestComponent();
                            httpRequestComponent.set_method("POST");
                            for(std::string host_path : id(scene_light_host_string_1)) {
                                httpRequestComponent.set_url("http://" +host_path + "/set?value=" + std::to_string(int(x)));
                                httpRequestComponent.send({});
                            }
                            httpRequestComponent.close();
                            return;
                        } else {
                            if(0 == x) {
                                id(shelly_relay_1).turn_off();
                            } else {
                                id(shelly_relay_1).turn_on();
                            }
                       }


sun:
  on_sunrise:
    - then:
    - elevation: ${sunrise_elevation} 
      then: 
        - if:
             condition:
               - lambda: return  ${sunrise_enabled};
             then:
               - number.set:
                   id: "${device_name}_scene"
                   value: ${sunrise_scene}

  on_sunset:
    - then:
    - elevation: ${sunset_elevation} 
      then: 
        - if:
             condition:
               - lambda: return  ${sunset_enabled};
             then:
               - number.set:
                   id: "${device_name}_scene"
                   value: ${sunset_scene}

packages:
  base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/pm-esp8266.yaml
    refresh: 1s
  sun: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/sun.yaml
    refresh: 1d
  ping: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/ping.yaml
    refresh: 1d