#source for orginal: https://www.esphome-devices.com/devices/Shelly-1PM
#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
substitutions:
  max_power: "1000.0"
  restore_mode_2: RESTORE_DEFAULT_ON
  light_automation_input_number_max_2: '2'
  scene_light_host_string_2: ""
  scene_master_host_2: ""
  light_settings_string_2: '{{"light.turn_off"},{"light.turn_on","kelvin","2700","brightness_pct","30"},{"light.turn_on","kelvin","4587","brightness_pct","100"}}'
  light_entities_count_2: "2"
  scene_icon_2: "mdi:ceiling-light-outline"
  friendly_relay_name_1: "${friendly_name} A"
  device_relay_name_1: "${device_name}_a"
  friendly_relay_name_2: "${friendly_name} B"
  device_relay_name_2: "${device_name}_b"


packages:
  base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/1pm.yaml
    refresh: 1s
  sun: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/sunnier.yaml
    refresh: 1s