globals:
   - id: previous_temp
     type: float
     restore_value: false
     initial_value: '3'

substitutions:
  device_type: "thermometer"
  device_type_nice: "Thermometer"
  dallas_address: "0X0000 whatever"
  dallas_pin: "GPI0 whatever"
  dallas_temp_update_url: "http://whatever"
  dallas_update: 15s

dallas:
  - pin: ${dallas_pin}
    id: ${device_name}_pin
    update_interval: ${dallas_update}

sensor:
  - platform: dallas
    address: ${dallas_address}
    name: ${friendly_name}
    id: ${device_name}
    icon: mdi:thermometer
    dallas_id: ${device_name}_pin
    on_value:
      then:
      - if:
            condition:
              - lambda: |- 
                  if (x != id(previous_temp)) {
                     id(previous_temp) = x;
                     return true;
                  }
                  return false;
            then:
              - http_request.post: !lambda |- 
                      return "${dallas_temp_update_url}" + std::to_string(x);

packages:
  device-base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/esp8266.yaml
    refresh: 1s
  sun: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/base/sun.yaml
    refresh: 1d