substitutions:
  device_type: "thermometer"
  device_type_nice: "Thermometer"
  dallas_address: "sensor address"

dallas:
  - pin: GPIO5

sensor:
  - platform: dallas
    address: $dallas_address
    name: ${friendly_name}
    id: $name

packages:
  device-base: 
    url: https://github.com/snetsplit/esphome-automation
    file: yaml/ESP8266-boiler-plate.yaml
    refresh: 0s
