#NOT COMPLETE. NOT WARRENTIED. USE AT OWN RISK.
#provided as is, but feel free to learn, copy, and use, but at own risk.
#this file has stuff used in pretty much every ESP8266 yaml file I have.
substitutions:
  nice_name: "ESPHome"
  sys_name: "esphome"
  device_type: "device"
  device_type_nice: "Device"
  name: ${sys_name}-${device_type}
  device_name: ${sys_name}_${device_type}
  friendly_name: "${nice_name} ${device_type_nice}"
  web_server_port: "80"
  ssid: "IP freely"
  password: "ewwwwwwwww"
  domain: ".local"
  time_server1: "0.pool.ntp.org"
  time_server2: "1.pool.ntp.org"
  time_server3: "2.pool.ntp.org"
  ota_password: "wouldn't you like to know?"
  latitude: 48.8584°
  longitude: 2.2945°
  
logger:

api:

ota:
  password:  ${ota_password}

captive_portal:

wifi:
  ssid: ${ssid}
  password: ${password}
  domain: ${domain}
  ap:
    ssid: "${friendly_name} Fallback"
    password: ${password}
  power_save_mode: high

web_server:
  port: ${web_server_port}
  version: 2
  js_url: https://home.lan/local/_static/v2/www.js
  local: true

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - ${time_server1}
      - ${time_server2}
      - ${time_server3}

http_request:
  id: http_request_data
  useragent: esphome/device
  timeout: 10s
  esp8266_disable_ssl_support: true

esphome:
  name: ${name}
  comment: ${friendly_name}
  platform: ESP8266
  board: esp01_1m

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: ${sys_name}_${device_type}_uptime_sensor
    icon: mdi:clock-start
    update_interval: 60s
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    id: ${sys_name}_${device_type}_wifi_signal
    update_interval: 60s


text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version
    id: ${sys_name}_${device_type}_esphome_version    
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      id: ${sys_name}_${device_type}_ip_address
      icon: mdi:ip-network
  - platform: template
    name: "Current time"
    lambda: |-
      char str[17];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M", localtime(&currTime));
      return  { str };
    update_interval: 60s

button:
  - platform: restart
    id: ${sys_name}_${device_type}_restart_button
    name: "${friendly_name} Restart"
