globals:
   - id: auto_mode
     type: bool
     restore_value: true
     initial_value: 'false'
   - id: outside_temp_minimum
     type: float
     restore_value: false
     initial_value: '11'
   - id: outside_temp_maximum
     type: float
     restore_value: true
     initial_value: '3'
   - id: previous_target_temp
     type: float
     restore_value: false
     initial_value: '3'
   - id: cool_on_temp
     type: float
     restore_value: false
     initial_value: '3'
   - id: heat_on_temp
     type: float
     restore_value: false
     initial_value: '3'
   - id: turbo_cool_on_temp
     type: float
     restore_value: false
     initial_value: '3'
   - id: turbo_heat_on_temp
     type: float
     restore_value: false
     initial_value: '3'
   - id: turbo_cool_off_temp
     type: float
     restore_value: false
     initial_value: '3'
   - id: turbo_heat_off_temp
     type: float
     restore_value: false
     initial_value: '3'
   - id: cooling_room
     type: boolean
     restore_value: false
     initial_value: 'false'

substitutions:
  name: slwf-01pro-heatpump # Use a unique name.
  id: slwf_01pro_heatpump    # Use a unique id.
  friendly_name: "SLWF-01pro Heatpump"
  web_server_port: "80"
  ssid: "IP freely"
  password: "ewwwwwwwww"
  domain: ".local"
  time_server1: "0.pool.ntp.org"
  time_server2: "1.pool.ntp.org"
  time_server3: "2.pool.ntp.org"
  heat_on: "-2"
  cool_on: "4"
  heat_turbo_on: "-2"
  cool_turbo_on: "4"
  heat_turbo_off: "2"
  cool_turbo_off: "0"
  outside_temp_minimum_difference: "5.4"
  outside_temp_maximum_difference: "3"
esphome:
  name: ${name}
  comment: ${friendly_name}
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 600
    then:
      lambda: |-
         id(${id}_beeper).turn_on();

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - ${time_server1}
      - ${time_server2}
      - ${time_server3}

wifi:
  ssid: ${ssid}
  password: ${password}
  domain: ${domain}
  ap:
    ssid: "${friendly_name} Fallback"
    password: ${password}
  power_save_mode: high

web_server:
  port: ${web_server_port}
  local: true


captive_portal:

# Enable Home Assistant API
api:

# Enable Over The Air updates
ota:

logger:
  level: WARN

# Binary 
binary_sensor:
  - platform: status
    name: ${friendly_name} Connection Status
    id: ${id}_connection_status

# Sensors.
sensor:
  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${friendly_name} Temperature
    unit_of_measurement: "°c"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0
  - platform: uptime
    name: Uptime Sensor
    id: ${id}_uptime_sensor
    icon: mdi:clock-start
    update_interval: 60s
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    id: ${id}_wifi_signal
    update_interval: 60s
  - platform: template
    name: ${friendly_name} Outside off low
    id: ${id}_temp_off_low
    unit_of_measurement: °C
  - platform: template
    name: ${friendly_name} Outside off high
    id: ${id}_temp_off_high
    unit_of_measurement: °C
  - platform: template
    name: ${friendly_name} Cool temp
    id: ${id}_temp_cool
    unit_of_measurement: °C
  - platform: template
    name: ${friendly_name} heat temp
    id: ${id}_temp_heat
    unit_of_measurement: °C
  - platform: template
    name: ${friendly_name} turbo cool on above set temp
    id: ${id}_temp_cool_turbo_on
    unit_of_measurement: °C
  - platform: template
    name: ${friendly_name} turbo heat on below set temp
    id: ${id}_temp_heat_turbo_on
    unit_of_measurement: °C
  - platform: template
    name: ${friendly_name} turbo heat off above set temp
    id: ${id}_temp_heat_turbo_off
    unit_of_measurement: °C
  - platform: template
    name: ${friendly_name} turbo cool off below set temp
    id: ${id}_temp_cool_turbo_off
    unit_of_measurement: °C
     
  
# Text Sensors.
text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version
    id: ${id}_esphome_version    
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      id: ${id}_ip_address
      icon: mdi:ip-network

switch:
  - platform: template
    name: ${friendly_name} Beeper
    id: ${id}_beeper
    icon: mdi:volume-source
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:
  - platform: template
    name: ${friendly_name} Auto Mode
    id: ${id}_auto_mode
    icon: mdi:car-turbocharger
    optimistic: true
    lambda: return id(auto_mode);  
    turn_on_action:
        - lambda: |-
            id(auto_mode) = true;
            id(${id}_automation_lambda).press();
    turn_off_action:
        - lambda: |-
            id(auto_mode) = false;

button:
  - platform: restart
    id: ${id}_restart_button
    name: "${friendly_name} Restart"
  - platform: template
    name: "${friendly_name} Display Toggle"
    id: ${id}_display_toggle
    icon: mdi:theme-light-dark
    on_press:
      midea_ac.display_toggle:
             
  - platform: template
    internal: true
    id: ${id}_automation_lambda
    on_press:
        - lambda: |-
                  if (id(auto_mode)) {

                      ESP_LOGW(
                              "climate_temp", "target: %f°C, room: %f°C", 
                              (id(${id}_my_climate).target_temperature * 1.8 + 32),
                              (id(${id}_room_temperature).state * 1.8 + 32)
                      );
                       if (
                              (id(${id}_room_temperature).state < id(cool_on_temp))
                              && !id(cooling_room)
                              && (id(${id}_outside_tempreture).state > id(outside_temp_minimum)) 
                              && (id(${id}_outside_tempreture).state < id(outside_temp_maximum))
                          ) {
                           if (ClimateMode::CLIMATE_MODE_OFF != id(${id}_my_climate).mode) {
                              id(${id}_my_climate).make_call().set_preset(ClimatePreset::CLIMATE_PRESET_NONE).perform();
                              delay(2000);
                              id(${id}_my_climate).make_call().set_mode(ClimateMode::CLIMATE_MODE_OFF).perform();
                           }                           
                       } else if(id(${id}_room_temperature).state < id(heat_on_temp) ) {
                           if (id(cooling_room)) {
                                 id(cooling_room) = false;
                           } else if (ClimateMode::CLIMATE_MODE_HEAT != id(${id}_my_climate).mode) {
                              id(${id}_my_climate).make_call().set_mode(ClimateMode::CLIMATE_MODE_HEAT).perform();
                           }
                           delay(2000);
                           if(id(${id}_room_temperature).state < id(turbo_heat_on_temp)) {
                               if (ClimatePreset::CLIMATE_PRESET_BOOST !=  id(${id}_my_climate).preset.value()) {
                                  id(${id}_my_climate).make_call().set_preset(ClimatePreset::CLIMATE_PRESET_BOOST).perform();
                               } else if (id(${id}_room_temperature).state > id(turbo_heat_off_temp)) {
                               if (ClimatePreset::CLIMATE_PRESET_NONE !=   id(${id}_my_climate).preset.value()) {
                                  id(${id}_my_climate).make_call().set_preset(ClimatePreset::CLIMATE_PRESET_NONE).perform();
                               }
                              }
                           }
                      } else if(id(${id}_room_temperature).state > id(cool_on_temp) ) {
                           if (ClimateMode::CLIMATE_MODE_COOL != id(${id}_my_climate).mode) {
                              id(${id}_my_climate).make_call().set_mode(ClimateMode::CLIMATE_MODE_COOL).perform();
                           }
                           delay(2000);
                           if (id(${id}_room_temperature).state > id(turbo_cool_on_temp)) {
                               if (ClimatePreset::CLIMATE_PRESET_BOOST !=  id(${id}_my_climate).preset.value()) {
                                  id(${id}_my_climate).make_call().set_preset(ClimatePreset::CLIMATE_PRESET_BOOST).perform();
                               } else if  (id(${id}_room_temperature).state < id(turbo_cool_off_temp)) {
                               if (ClimatePreset::CLIMATE_PRESET_NONE !=   id(${id}_my_climate).preset.value()) {
                                  id(${id}_my_climate).make_call().set_preset(ClimatePreset::CLIMATE_PRESET_NONE).perform();
                               }
                              }
                           }
                       } else {
                              ESP_LOGW("climate_mode", "Setting mode: [%s]",  "none");
                             }
                  }


select:
  - platform: template
    id: ${id}_my_climate_preset
    name: "${friendly_name} Preset"
    optimistic: true
    options:
      - "None"
      - Boost
      - Eco
      - Sleep
    initial_option: "None"
    on_value:
      then:
      - lambda: |-
           if(x == "None") {
            id(${id}_my_climate).make_call().set_preset(ClimatePreset::CLIMATE_PRESET_NONE).perform();
           }
           id(${id}_my_climate).make_call().set_preset(x).perform();
  - platform: template
    id: ${id}_my_climate_swing_mode
    name: "${friendly_name} Swing Mode"
    optimistic: true
    options:
      - "Off"
      - Vertical
    initial_option: "Off"
    on_value:
      then:
      - lambda: |-
           id(${id}_my_climate).make_call().set_swing_mode(x).perform();
  - platform: template
    id: ${id}_my_climate_fan_mode
    name: "${friendly_name} Fan Mode"
    optimistic: true
    options:
      - Auto
      - Low
      - Medium
      - High
      - Silent
      - Turbo
    initial_option: Auto
    on_value:
      then:
      - lambda: |-
           id(${id}_my_climate).make_call().set_fan_mode(x).perform();

number:
  - platform: template
    name: ${friendly_name} Room Tempreture
    id: ${id}_room_temperature
    optimistic: true
    min_value: -40
    max_value: 80
    restore_value: true
    unit_of_measurement: °C
    step: 0.1
    on_value:
      then:
        - lambda: |-
            id(${id}_automation_lambda).press();
         
         
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

climate:
  - platform: midea
    id: ${id}_my_climate
    name: ${friendly_name}
    supported_modes:
      - COOL
      - HEAT
      - DRY
    supported_presets:
      - ECO
      - BOOST
      - SLEEP
    custom_fan_modes:
    custom_presets:
      - FREEZE_PROTECTION
    supported_swing_modes:
      - VERTICAL
    outdoor_temperature:
      id: ${id}_outside_tempreture
      name: ${friendly_name} Outside Tempreture
      unit_of_measurement: °C
      on_value:
      - lambda: |-
            id(${id}_automation_lambda).press();
    on_state:
    - lambda: |-
         if(id(${id}_my_climate).target_temperature != id(previous_target_temp)) {
            id(previous_target_temp) = id(${id}_my_climate).target_temperature;
            id(cool_on_temp) = id(${id}_my_climate).target_temperature + $cool_on;
            id(heat_on_temp) = id(${id}_my_climate).target_temperature + $heat_on;
            id(turbo_cool_on_temp) = id(${id}_my_climate).target_temperature + $cool_turbo_on;
            id(turbo_heat_on_temp) = id(${id}_my_climate).target_temperature + $heat_turbo_on;
            id(turbo_cool_off_temp) = id(${id}_my_climate).target_temperature + $cool_turbo_off;
            id(turbo_heat_off_temp) = id(${id}_my_climate).target_temperature + $heat_turbo_off;
            id(outside_temp_maximum) = id(${id}_my_climate).target_temperature + ${outside_temp_maximum_difference};
            id(outside_temp_minimum) = id(${id}_my_climate).target_temperature - ${outside_temp_minimum_difference};
            id(${id}_temp_off_low).publish_state(id(outside_temp_minimum));
            id(${id}_temp_off_high).publish_state(id(outside_temp_maximum));
            id(${id}_temp_cool).publish_state(id(cool_on_temp));
            id(${id}_temp_heat).publish_state(id(heat_on_temp));
            id(${id}_temp_cool_turbo_on).publish_state(id(turbo_cool_on_temp));
            id(${id}_temp_heat_turbo_on).publish_state(id(turbo_heat_on_temp));
            id(${id}_temp_heat_turbo_off).publish_state(id(turbo_heat_off_temp));
            id(${id}_temp_cool_turbo_off).publish_state(id(turbo_cool_off_temp));
          } 
         id(${id}_automation_lambda).press();
             
